#!/bin/sh

# just in case, clean up any existing pierogi.sudoers file:
#rm /etc/sudoers.d/pierogi.sudoers

# now, create the file:
echo "user ALL = NOPASSWD: /opt/pierogi/bin/loadRX51Module
user ALL = NOPASSWD: /opt/pierogi/bin/unloadRX51Module" > /etc/sudoers.d/pierogi.sudoers

update-sudoers

exit 0
